import {auth,db} from "./firebase-config.js";
import {onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import {collection,getDocs,doc,getDoc,query,where,updateDoc} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import {updateDoc as firestoreUpdateDoc} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const $=s=>document.querySelector(s);
const escapeHtml=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function relogio(){const agora=new Date();const h=agora.getHours();$("#saudacao").textContent=h<12?"Bom dia ☀️":h<18?"Boa tarde 🌤️":"Boa noite 🌙";$("#horaAtual").textContent=agora.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});$("#dataAtual").textContent=agora.toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"})}
function dataHoje(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0`)}`}
function cardPagamento(a){return `<div style="margin-top:12px;padding:12px;border-radius:12px;background:#fff7ef;border:1px solid #ead7c4"><b>💰 Pagamento do atendimento</b><label>Valor pago</label><input data-valor-pago="${a.id}" type="number" step="0.01" min="0" value="${Number(a.valorPago??a.valor??0)||""}" placeholder="0,00"><label>Forma de pagamento</label><select data-pagamento="${a.id}"><option value="">Selecione</option><option value="pix">PIX</option><option value="dinheiro">Dinheiro</option><option value="credito">Cartão de crédito</option><option value="debito">Cartão de débito</option></select><button data-save-pagamento="${a.id}">💾 Salvar pagamento e concluir</button></div>`}
async function salvarPagamento(id){const valor=Number(document.querySelector(`[data-valor-pago="${id}"]`)?.value||0);const forma=document.querySelector(`[data-pagamento="${id}"]`)?.value||"";if(!valor||valor<0||!forma){alert("Informe o valor pago e a forma de pagamento.");return}await firestoreUpdateDoc(doc(db,"agendamentos",id),{valor,valorPago:valor,formaPagamento:forma,status:"concluido",pagamentoRegistradoEm:new Date().toISOString()});agenda()}
function cardAgendamento(a){return `<div class="appointment"><b>🕐 ${escapeHtml(a.horario||"")}</b> — ${escapeHtml(a.nome||"Cliente")}<br>📱 ${escapeHtml(a.telefone||"")}<br>💆 ${escapeHtml(a.servico||"")}<br><select data-status="${a.id}"><option ${a.status==="pendente"?"selected":""}>pendente</option><option ${a.status==="confirmado"?"selected":""}>confirmado</option><option ${a.status==="concluido"?"selected":""}>concluido</option><option ${a.status==="cancelado"?"selected":""}>cancelado</option></select>${a.status==="confirmado"?cardPagamento(a):""}</div>`}
function cardRealizado(a){const forma={pix:"PIX",dinheiro:"Dinheiro",credito:"Cartão de crédito",debito:"Cartão de débito"}[a.formaPagamento]||"Não informado";return `<div class="appointment"><b>✅ ${escapeHtml(a.horario||"")}</b> — ${escapeHtml(a.nome||"Cliente")}<br>📱 ${escapeHtml(a.telefone||"")}<br>💆 ${escapeHtml(a.servico||"")}<br>💰 <b>R$ ${Number(a.valorPago??a.valor??0).toFixed(2).replace(".",",")}</b> · ${forma}</div>`}
async function agenda(){const data=$("#filtroData").value||dataHoje();const q=query(collection(db,"agendamentos"),where("data","==",data));const s=await getDocs(q);const lista=s.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(a.horario||"").localeCompare(b.horario||""));const ativos=lista.filter(a=>a.status!=="concluido");const realizados=lista.filter(a=>a.status==="concluido");$("#agenda").innerHTML=ativos.length?ativos.map(cardAgendamento).join(""):"Nenhum agendamento pendente ou confirmado para esta data.";$("#realizados").innerHTML=realizados.length?realizados.map(cardRealizado).join(""):"Nenhum atendimento realizado nesta data.";document.querySelectorAll("[data-status]").forEach(el=>el.onchange=async()=>{const id=el.dataset.status;if(el.value==="confirmado"){await firestoreUpdateDoc(doc(db,"agendamentos",id),{status:"confirmado"});agenda()}else if(el.value==="concluido"){alert("Para concluir, informe primeiro o pagamento. O atendimento será concluído pelo botão 'Salvar pagamento e concluir'.");agenda()}else{await firestoreUpdateDoc(doc(db,"agendamentos",id),{status:el.value});agenda()}});document.querySelectorAll("[data-save-pagamento]").forEach(b=>b.onclick=()=>salvarPagamento(b.dataset.savePagamento))}
$("#filtroData").value=dataHoje();$("#filtroData").onchange=agenda;$("#logout").onclick=()=>signOut(auth);relogio();setInterval(relogio,1000);
onAuthStateChanged(auth,async u=>{if(!u){location.href="admin-login.html";return}const p=await getDoc(doc(db,"usuarios",u.uid));if(!p.exists()||p.data().tipo!=="admin"){location.href="index.html";return}agenda()});