import {auth,db} from "./firebase-config.js";
import {onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import {collection,getDocs,doc,getDoc,query,where,updateDoc} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const $=s=>document.querySelector(s);
const escapeHtml=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function relogio(){const agora=new Date();const h=agora.getHours();$("#saudacao").textContent=h<12?"Bom dia ☀️":h<18?"Boa tarde 🌤️":"Boa noite 🌙";$("#horaAtual").textContent=agora.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});$("#dataAtual").textContent=agora.toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"})}
function dataHoje(){return new Date().toISOString().slice(0,10)}
async function agenda(){const data=$("#filtroData").value||dataHoje();const q=query(collection(db,"agendamentos"),where("data","==",data));const s=await getDocs(q);const lista=s.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(a.horario||"").localeCompare(b.horario||""));$("#agenda").innerHTML=lista.length?lista.map(a=>`<div class="appointment"><b>🕐 ${escapeHtml(a.horario||"")}</b> — ${escapeHtml(a.nome||"Cliente")}<br>📱 ${escapeHtml(a.telefone||"")}<br>💆 ${escapeHtml(a.servico||"")}<br><select data-status="${a.id}"><option ${a.status==="pendente"?"selected":""}>pendente</option><option ${a.status==="confirmado"?"selected":""}>confirmado</option><option ${a.status==="concluido"?"selected":""}>concluido</option><option ${a.status==="cancelado"?"selected":""}>cancelado</option></select></div>`).join(""):"Nenhum agendamento para esta data.";document.querySelectorAll("[data-status]").forEach(el=>el.onchange=()=>updateDoc(doc(db,"agendamentos",el.dataset.status),{status:el.value}))}
$("#filtroData").value=dataHoje();$("#filtroData").onchange=agenda;$("#logout").onclick=()=>signOut(auth);relogio();setInterval(relogio,1000);
onAuthStateChanged(auth,async u=>{if(!u){location.href="admin-login.html";return}const p=await getDoc(doc(db,"usuarios",u.uid));if(!p.exists()||p.data().tipo!=="admin"){location.href="index.html";return}agenda()});